config/routes.rb
Rails.application.routes.draw do
  resource :github_webhooks, only: :create, defaults: { formats: :json }
  resources :tools, except: [:destroy, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tool.rb
class Tool < ApplicationRecord
  validates :name, :language, presence: true

  before_save { self.name.downcase! }

  scope :with_spec, -> { where.not(spec: nil) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/github_webhooks_controller.rb
class GithubWebhooksController < ActionController::Base
  skip_before_action :verify_authenticity_token
  include GithubWebhook::Processor

  def github_pull_request(payload)
    return unless payload['action'].eql?('closed') && payload['pull_request']['merged']
    
    number = payload['pull_request']['number']
    branch_name = payload['pull_request']['head']['ref']
    
    UpdateToolSpecJob.perform_later(number, branch_name)
  end


  private

  def webhook_secret(payload)
    ENV['GITHUB_WEBHOOK_SECRET']
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  before_action :set_tool, only: :update

  def index
    @tools = Tool.with_spec
  end

  def new
    @tool = Tool.new
  end

  def create
    tool = Tool.new(tool_params) 
    if tool.save
      CreateLokaliseTranslationsJob.perform_later(tool_params[:name], tool_params[:language])
      flash[:notice] = t('tool.create')
    else
      flash[:error] = t('error')
    end

    redirect_to new_tool_path
  end

  def edit
    @tool = Tool.find(params[:id])
  end

  def update
    branch_outcome = Github::FindBranchIntr.run(branch_name: branch_name)
    
    if branch_outcome.valid?
      flash[:error] = t('api.branch_error')
    else
      CreatePullRequestJob.perform_later(@tool.name, tool_params[:language], branch_name)
      flash[:notice] = t('tool.update')
    end
    
    redirect_to new_tool_path
  end

  private

  def tool_params
    params.require(:tool).permit(:name, :language)
  end

  def set_tool
    @tool = Tool.find(params[:id])
  end

  def branch_name
    "#{@tool.name}-#{tool_params[:language]}-spec"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MediatelyTestTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tools/_form.html.erb
<%= form_with(model: tool, local: true) do |form| %>
  <% if tool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tool.errors.count, "error") %> prohibited this tool from being saved:</h2>

      <ul>
      <% tool.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.label :name %>
    <%= form.text_field :name, disabled: !tool.new_record? %>
    <%= form.label :language %>
    <%= form.text_field :language %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tools/edit.html.erb
<h1>Editing Tool</h1>

<%= render 'form', tool: @tool %>

<%= link_to 'Show', @tool %> |
<%= link_to 'Back', tools_path %>

app/views/tools/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Tools</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tools.each do |tool| %>
      <tr>
        <td><%= link_to 'Edit', edit_tool_path(tool) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tool', new_tool_path %>

app/views/tools/new.html.erb
<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
</div>
<h1>New Tool</h1>

<%= render 'form', tool: @tool %>

<%= link_to 'Back', tools_path %>